services:
  express:
    container_name: express
    image: snic0n/uoh-ex3-1
    ports: 
      - 8080:8080
    labels:
      - "com.centurylinklabs.watchtower.enable=true"


  watchtower:
    image: nickfedor/watchtower
    environment:
      -  WATCHTOWER_POLL_INTERVAL=60 # Poll every 60 seconds
      -  WATCHTOWER_LABEL_ENABLE=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: watchtower